import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { API_URL } from "../config";

// Define a service using a base URL and expected endpoints
export const flowerApi = createApi({
  reducerPath: "flowerManagement",
  // Tag types are used for caching and invalidation.
  tagTypes: ["FlowerList"],
  baseQuery: fetchBaseQuery({ baseUrl: API_URL }),
  endpoints: (builder) => ({
    // Supply generics for the return type (in this case `FlowerApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getFlowers: builder.query({
      query: () => `flowerManagement`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, _error, _arg) =>
        result
          ? [
              ...result.map(({ id }) => ({ type: "flowerManagement", id })),
              { type: "FlowerList", id: "LIST" },
            ]
          : [{ type: "FlowerList", id: "LIST" }],
    }),
    addFlower: builder.mutation({
      query: (body) => {
        return {
          method: "POST",
          url: `flowerManagement`,
          body,
        };
      },
      invalidatesTags: [{ type: "FlowerList", id: "LIST" }],
    }),
    editFlower: builder.mutation({
      query: (payload) => {
        return {
          method: "PUT",
          url: `flowerManagement/` + payload.id,
          body: payload.body,
        };
      },
      invalidatesTags: (res, err, arg) => [{ type: "FlowerList", id: arg.id }],
    }),
    deleteFlower: builder.mutation({
      query: (payload) => {
        return {
          method: "DELETE",
          url: `flowerManagement/` + payload.id,
        };
      },
      invalidatesTags: (_res, _err, _arg) => [
        { type: "FlowerList", id: "LIST" },
      ],
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
// Hooks are auto-generated by RTK-Query
export const {
  useGetFlowersQuery,
  useAddFlowerMutation,
  useEditFlowerMutation,
  useDeleteFlowerMutation,
} = flowerApi;
